language: ruby
ruby: '2.2.2'
install: echo "skip install"
branches:
  only: iu-nightly
after_success:
- chmod 600 deploy-key
- ssh -i deploy-key pdinh@beryllium.dlib.indiana.edu 'touch travised'
before_install:
- echo -e "Host example.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_aa7412036b4c_key -iv $encrypted_aa7412036b4c_iv
  -in deploy_key.enc -out deploy_key -d
