#!/usr/bin/env ruby
#require 'bcrypt'
require 'yaml'

file = ARGV[0]
facts = YAML.load(File.read(file))
unless facts['avalon_dropbox_password'].nil?
  salt = rand(36**8).to_s(36)
  facts['avalon_dropbox_password_hash'] = facts['avalon_dropbox_password'].crypt("$1$#{salt}$")
  facts['avalon_dropbox_password'] = nil
end

#unless facts['avalon_admin_password'].nil?
#  facts['avalon_admin_password_hash'] = BCrypt::Password.create(facts['avalon_admin_password'])
#  facts['avalon_admin_password'] = nil
#end
File.open(file,'w') { |f| f.write(YAML.dump(facts)) }